# SwiftLint Configuration for FameFit App

# Paths to include
included:
  - FameFit Watch App
  - FameFit Watch AppTests
  - FameFit
  - FameFitTests

# Paths to exclude
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - ${PWD}/**/*.generated.swift

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace
  - force_cast
  - force_try

# Rule configurations
line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - PR
    - to
    - on
    - ok

# Custom rules
custom_rules:
  # Disabled for development - enable for production
  # no_print_statements:
  #   name: "No print statements"
  #   message: "Use proper logging instead of print statements"
  #   regex: "(^\\s*print\\()|(NSLog\\()"
  #   match_kinds:
  #     - identifier
  #   severity: warning
  
  no_force_unwrapping:
    name: "Avoid Force Unwrapping"
    message: "Force unwrapping should be avoided"
    regex: "[^!]=\\s*\\w+!"
    severity: warning